Adding Pipewire watch recipe
awesomeWM/awesome-www pull request #167
Opened 2022-06-18 12:30 UTC by dixiedream

A simple volume widget for pure Pipewire systems.

2022-06-18 12:46 UTC, Aire-One requested changes

2022-06-18 12:46 UTC, Aire-One commented on recipes/watch.mdwn
> +```lua
I think we need an extra empty line here to allow the markdown interpreter to work :

```suggestion
## pipewire

```lua
```

2022-06-18 12:50 UTC, dixiedream commented
@Aire-One Thanks!

2022-06-18 12:57 UTC, Aire-One approved these changes
Thank you!

2022-06-18 19:37 UTC, Elv13 approved these changes

2022-06-18 19:37 UTC, merged

2022-06-19 06:12 UTC, psychon commented
Correct me if I am wrong, but `pactl` is part of PulseAudio and not pipewire.
```
$ man -k pactl
pactl (1)            - Control a running PulseAudio sound server
```

2022-06-19 07:14 UTC, dixiedream commented
You're absolutely right but it will also been installed by `pipewire-pulse` which is the only package you need in order to make pulse based apps on pipewire.